### ISSUE TITLE
Error: INSTALLATION FAILED: create: failed to create: Request entity too large: limit is 3145728

### ISSUE THREAD

**Issue by AndreiBanaruTakeda** [aws-observability/aws-otel-helm-charts#30] opened 2022-04-07 14:39 UTC
Installing the chart is not possible anymore.

Simple installation via helm:
```
helm install cloudwatch-container-insights aws-observability/adot-exporter-for-eks-on-ec2 -f values.yml
```

will fail with:
```
Error: INSTALLATION FAILED: create: failed to create: Request entity too large: limit is 3145728
```

I think the [documentation](https://github.com/aws-observability/aws-otel-helm-charts/tree/master/charts/adot-exporter-for-eks-on-ec2/documentation) directory can be safely added to _.helmignore_

**Comment by steveellis** [comment] 2022-04-07 15:19
Would bet it is those screenshots in the docs are what is to blame: https://github.com/aws-observability/aws-otel-helm-charts/tree/master/charts/adot-exporter-for-eks-on-ec2/documentation/screenshots.

**Comment by sunnygoel87** [comment] 2022-04-07 19:38
> Would bet those screenshots in the docs are what is pushing it over the limit: https://github.com/aws-observability/aws-otel-helm-charts/tree/master/charts/adot-exporter-for-eks-on-ec2/documentation/screenshots.

PDF alone is 1.28 MB in size and 2 screeenshots together add another ~ 1MB.

**Comment by sunnygoel87** [comment] 2022-04-07 19:39
@alolita @ruthvik17 , Just FYI. Can someone fix this quickly ?

**Comment by sunnygoel87** [comment] 2022-04-08 07:38
@steveellis @AndreiBanaruTakeda - The issue has been fixed. I was able to deploy the Helm chart successfully. Please try and let us know if you still face any issue. Thanks.

**Comment by steveellis** [comment] 2022-04-08 16:44
@sunnygoel87 I can confirm on my end that with the new version 0.3.1 this error is gone.

**Comment by ruthvik17** [comment] 2022-04-08 16:51
Closing this issue since the error has been resolved.

**Closed by ruthvik17** 2022-04-08 16:51 UTC
